<?php

namespace TransportBundle\Repository;

use Doctrine\DoctrineExtensions\Query\Mysql;
/**
 * VehicleRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleRequestRepository extends \Doctrine\ORM\EntityRepository
{
	public function getRequestByMonth($month, $year, $category) {
		
		$request = $this->createQueryBuilder('r')
			->where('YEAR(r.date) = ' . $year)
			->andWhere('MONTH(r.date) = ' . $month)
			->andWhere('r.category = ' . $category)
			->getQuery()
			->getResult();
		return $request;
	}
}
